### PR TITLE
Remove XItemLib, use a base game-oriented fix for item odds

### PR DESCRIPTION
**Pull request by JugadorXEI**
Removes XItemLib - instead when a player is about to roll an item, this player and all players ahead are teleported to the Past in PreThinkFrame and teleported back in PlayerThink so they are none the wiser that this teleport even occurred. This allows them to roll for their item correctly.

This script is based on an earlier pre-release version, but with all the kinks ironed out - it should play nicer and not give 1st a random Invincibility when players get an item at the same time (a surprisingly common occurrence in testing, I found.)

Fixes nearly every problem related with the XItemLib integration because XItemLib does no longer exist. Hooray.

### CODE REVIEW

**Comment by JugadorXEI** [comment]
Did a 3-player netgame test and seems to be working fine, but I will try to test on a bigger netgame test before putting it on master.

**Comment by GenericHeroGuy** [comment]
Interesting stuff!
Though, while testing offline, I discovered a bug; with only two players next to each other, the player with the higher ID gets maxed out odds if they're on a different timeline than the other player:
brokenodds

**Comment by JugadorXEI** [comment]
Yeah - I guess this is the logical result if I'm only having the last player remove the odds-controlling teleport during PlayerThink. It's a shame because this method is _almost_ unnoticeable compared to ThinkFrame, where you can briefly see the player pop in and out of existence, but just for fairness' sake I may move it back to ThinkFrame and encourage people to use XItemLib if the visual oddity bothers them.

Edit: Actually, I can have a combination of both, and move the last player in ThinkFrame, which should be extremely unnoticeable, I think I'd much rather prefer that to avoid visual bugs.

**Comment by JugadorXEI** [comment]
Apparently `isLastPlayer` never worked to begin with - fixing that fixes the issue you reported @GenericHeroGuy, although a second look couldn't hurt.

**Comment by JugadorXEI** [comment]
Here goes nothing.

**Pull request merged**
